### ISSUE TITLE
Review Ticket Week 4

### ISSUE THREAD

**Issue by ProRichyMan** [jar04/flask_portfolio#28]

**Comment by ProRichyMan** [comment]
Nathan: 
<img width="516" alt="Screen Shot 2022-01-06 at 12 54 26 PM" src="https://user-images.githubusercontent.com/89236893/148450532-cf27ea74-bd6d-4189-89a1-e212e40bb88d.png">
Accomplishments -
Navbar time and dark mode
SCSS
World Clock API for UTC time

**Comment by Danny4w** [comment]
![image](https://user-images.githubusercontent.com/89228041/148452290-faa1ac45-e118-4a0a-bf8b-3dd8b18e03a6.png)

Mainly worked on the overall design of the website:
-worked on adding new backgrounds and removing some of the texts that were forked from nighthawkcsp.
-redesigned home page and added a home page text that introduces our website
-about page changes: background, changed api to science articles, and wrote a description about my self. I also did the blueprints for the python files in intelliJ and linked that in the about page  
-other technicals: feedback page is finished. in progress: fixing weather api and language translator

**Comment by Reem57** [comment]
![mcq practice](https://user-images.githubusercontent.com/89223508/148837181-46190301-e07e-4706-ba69-b75e37d91711.png)

This week I mainly worked on the dropdown and sorting in search.
I also helped Nathan with some of the SCSS and dark mode/clock in the navbar.

For this week my plan is to look more into the design of our project because creating the dropdown created some design flaws and problems. I am also going to work on the CSS for my about me page so I have more things there and it looks neater.
self grade: 4.5

**Comment by JL1080** [comment]
This week worked on darkmode and tried to get SCSS working 
Tryed to add another API but it wouldn't work so trying to trouble shoot it.

Grade: 3.5
